### ISSUE TITLE
Downloading `amplify_outputs.json` from Amplify console doesn't work anymore

### ISSUE THREAD

**Issue by vandaeldev** [aws-amplify/amplify-backend#1914] opened 2024-08-26 10:50 UTC
### Environment information

```plain text
System:
  OS: Windows 11 10.0.22631
  CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
  Memory: 4.74 GB / 15.35 GB
Binaries:
  Node: 22.6.0 - ~\AppData\Local\fnm_multishells\21080_1724660645126\node.EXE
  Yarn: undefined - undefined
  npm: 10.8.2 - ~\AppData\Local\fnm_multishells\21080_1724660645126\npm.CMD
  pnpm: 9.8.0 - ~\AppData\Local\pnpm\pnpm.EXE
NPM Packages:
  @aws-amplify/auth-construct: 1.3.0
  @aws-amplify/backend: 1.1.1
  @aws-amplify/backend-auth: 1.1.3
  @aws-amplify/backend-cli: 1.2.5
  @aws-amplify/backend-data: 1.1.2
  @aws-amplify/backend-deployer: 1.1.0
  @aws-amplify/backend-function: 1.3.4
  @aws-amplify/backend-output-schemas: 1.2.0
  @aws-amplify/backend-output-storage: 1.1.1
  @aws-amplify/backend-secret: 1.1.0
  @aws-amplify/backend-storage: 1.1.2
  @aws-amplify/cli-core: 1.1.2
  @aws-amplify/client-config: 1.2.1
  @aws-amplify/deployed-backend-client: 1.4.0
  @aws-amplify/form-generator: 1.0.1
  @aws-amplify/model-generator: 1.0.5
  @aws-amplify/platform-core: 1.0.6
  @aws-amplify/plugin-types: 1.2.1
  @aws-amplify/sandbox: 1.2.0
  @aws-amplify/schema-generator: 1.2.1
  aws-amplify: 6.5.2
  aws-cdk: 2.154.1
  aws-cdk-lib: 2.154.1
  typescript: 5.5.4
AWS environment variables:
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
  AWS_STS_REGIONAL_ENDPOINTS = regional
No CDK environment variables
```

## Problem

After deploying my app to AWS Amplify, trying to download the `amplify_outputs.json` file from the Amplify console gives an error:

![Screenshot 2024-08-26 122927](https://github.com/user-attachments/assets/a5938115-8762-4e77-a356-00d81db92329)

![image](https://github.com/user-attachments/assets/29c73337-adfb-453b-a373-f130bc8807df)

This happens in spite of every resource created fresh, as it's a first deployment.

## App info
The app in question is using the latest versions (at time of writing) of the `aws-amplify` packages:

![image](https://github.com/user-attachments/assets/a8cb7278-9d82-4db8-89e4-320f2b78d6a8)

Besides basic `auth`, `data` and `storage` definitions, the app also uses a basic HTTP API created in the `backend.ts` file. This is included with the `backend.addOutput()` method, per documentation guidelines:

![image](https://github.com/user-attachments/assets/22b8006d-6f64-4244-875b-ed81c64d8253)

I don't specify a `version` here, because the default should be `'1.1'`.

## Expectation
I would expect that when an app gets deployed for the first time that every resource gets created according to the same schema version and that there shouldn't be a mismatch, like the error seems to be indicating.

**Comment by Jay2113** [comment] 2024-08-26 14:37
Hi @vandaeldev 👋 , thanks for raising this! I was able to reproduce this issue and marking as a bug.

**Comment by ioanabrooks** [comment] 2024-08-27 00:22
Hi @vandaeldev, the fix has been deployed. Please give it a try and let us know if you encounter any other issues!

**Comment by vandaeldev** [comment] 2024-08-27 06:55
@Jay2113 @ioanabrooks I can confirm it works again. Thanks for the quick fix and response!

**Closed** 2024-08-27 10:55 UTC
Labels: bug, console

**Comment by carlos-naranjo-aa** [comment] 2024-08-27 15:23
Yesterday i was able to download amplify_outputs.json now i cannot download it anymore. whatever you did it broke at least by console ability to download it. I try to deploy in a new application and in a new region , both in the us and India and it did not work

**Comment by jshamel** [comment] 2024-08-27 18:02
Trying to download it right now and it is not working ( in Chrome and Edge )

**Comment by dagnym** [comment] 2024-09-26 23:54
the option to download amplify_outputs is only showing on the gen 2 docs example project - yet it is not showing up on any of my other projects, despite the backend resources being successfully deployed. any idea why this is? i'm using the same yml

**Comment by tylerlan-rhizome** [comment] 2024-12-09 19:08
Hey all! I think I am experiencing something similar to @dagnym; I cloned the [amplify-next-template](https://github.com/aws-samples/amplify-next-template) and followed [the Amplify Gen 2 Quickstart example](https://docs.amplify.aws/nextjs/start/quickstart/nextjs-app-router-client-components/#:~:text=At%20the%20bottom%20of%20the%20page%20you%20will%20see%20a%20tab%20for%20Deployed%20backend%20resources.%20Click%20on%20the%20tab%20and%20then%20click%20the%20Download%20amplify_outputs.json%20file%20button.) to the letter. However, when it comes to the step of clicking the "Download amplify_outputs.json" button, I can't do it because the button simply is **NOT PRESENT** in the GUI,
<img width="962" alt="Screenshot 2024-12-09 at 11 02 51 AM" src="https://github.com/user-attachments/assets/236556d5-b528-4256-85ae-7ece955bc55d">

I know it's not a permissions thing because I paired with the Admin and they don't see the button either.

**Comment by tylerlan-rhizome** [comment] 2024-12-09 22:18
> Hey all! I think I am experiencing something similar to @dagnym; I cloned the [amplify-next-template](https://github.com/aws-samples/amplify-next-template) and followed [the Amplify Gen 2 Quickstart example](https://docs.amplify.aws/nextjs/start/quickstart/nextjs-app-router-client-components/#:~:text=At%20the%20bottom%20of%20the%20page%20you%20will%20see%20a%20tab%20for%20Deployed%20backend%20resources.%20Click%20on%20the%20tab%20and%20then%20click%20the%20Download%20amplify_outputs.json%20file%20button.) to the letter. However, when it comes to the step of clicking the "Download amplify_outputs.json" button, I can't do it because the button simply is **NOT PRESENT** in the GUI, <img alt="Screenshot 2024-12-09 at 11 02 51 AM" width="962" src="https://private-user-images.githubusercontent.com/156947089/393970205-236556d5-b528-4256-85ae-7ece955bc55d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3ODI3NzEsIm5iZiI6MTczMzc4MjQ3MSwicGF0aCI6Ii8xNTY5NDcwODkvMzkzOTcwMjA1LTIzNjU1NmQ1LWI1MjgtNDI1Ni04NWFlLTdlY2U5NTViYzU1ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwOVQyMjE0MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lM2MwNGI0MWMwY2RlOWQ1MWU1NTIxMjJlMDcyMjg5ZDQ3NTFmZDA3YjA2MTNiYjNlMDBkNGJmNjYyMGFmNzVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.U8MfQpbz3PllSVrLI6v_hzVuZSf_qKNB93NE7CCDgI4">
> 
> I know it's not a permissions thing because I paired with the Admin and they don't see the button either.

✅ SOLVED: Clear browser cache, log back in, wait 10 minutes, and presto! The button re-appears.

The part of this that is still confusing to me is why my team's Admin, using his own machine--not related to my OS or browser config--was able to independently verify this issue, and yet now, having changed nothing on his end, he also sees that the button has been restored...

**Comment by PulasthiAbey** [comment] 2025-02-07 03:49
> > Hey all! I think I am experiencing something similar to [@dagnym](https://github.com/dagnym); I cloned the [amplify-next-template](https://github.com/aws-samples/amplify-next-template) and followed [the Amplify Gen 2 Quickstart example](https://docs.amplify.aws/nextjs/start/quickstart/nextjs-app-router-client-components/#:~:text=At%20the%20bottom%20of%20the%20page%20you%20will%20see%20a%20tab%20for%20Deployed%20backend%20resources.%20Click%20on%20the%20tab%20and%20then%20click%20the%20Download%20amplify_outputs.json%20file%20button.) to the letter. However, when it comes to the step of clicking the "Download amplify_outputs.json" button, I can't do it because the button simply is **NOT PRESENT** in the GUI, <img alt="Screenshot 2024-12-09 at 11 02 51 AM" width="962" src="https://private-user-images.githubusercontent.com/156947089/393970205-236556d5-b528-4256-85ae-7ece955bc55d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3ODI3NzEsIm5iZiI6MTczMzc4MjQ3MSwicGF0aCI6Ii8xNTY5NDcwODkvMzkzOTcwMjA1LTIzNjU1NmQ1LWI1MjgtNDI1Ni04NWFlLTdlY2U5NTViYzU1ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwOVQyMjE0MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lM2MwNGI0MWMwY2RlOWQ1MWU1NTIxMjJlMDcyMjg5ZDQ3NTFmZDA3YjA2MTNiYjNlMDBkNGJmNjYyMGFmNzVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.U8MfQpbz3PllSVrLI6v_hzVuZSf_qKNB93NE7CCDgI4">
> > I know it's not a permissions thing because I paired with the Admin and they don't see the button either.
> 
> ✅ SOLVED: Clear browser cache, log back in, wait 10 minutes, and presto! The button re-appears.
> 
> The part of this that is still confusing to me is why my team's Admin, using his own machine--not related to my OS or browser config--was able to independently verify this issue, and yet now, having changed nothing on his end, he also sees that the button has been restored...

I tried this but still i can't see the button in the GUI
