### ISSUE TITLE
Unable To Add Redirects 

### ISSUE THREAD

**Issue by adsoink** [aws-amplify/amplify-backend#1565] opened 2024-05-28 03:40 UTC
### Environment information

```plain text
Please provide information as to where this needs to be copied/pasted for the correct output. There is no terminal in my instance of Amplify, so this piece is desperately unclear.
```

### Description

Howdy!

Looks like there may be a bug in the redirection feature in Amplify. We are currently leveraging this to redirect all traffic from outside the US to another domain; I'm currently unable to add new redirects due to a persistent error stating there's an error with the implementation of ISO-3166 region codes. 

Steps taken:

- Regressed all region codes input and saw no error.
- Rewrote the region-based redirects and the error persists.

We're in the middle of revamping landing pages, and will need this piece available to me ASAP. Any and all help is appreciated.

**Comment by adsoink** [comment] 2024-05-28 03:43
Please note that the above issue is new, and has only presented since the UI change with Amplify. I was able to input a redirect with no issue. Again - all country codes are ISO-3166 compliant and there is no error outside of the UI refusing to save after a new redirect has been input.

**Comment by adsoink** [comment] 2024-05-29 01:01
Hey Jay,

Thanks very much for the response. In answer to your question, the region-based redirects are formed correctly per the screenshot below. The redirect at the bottom of the image is one of three I'm attempting to insert as the page has obviously moved so as to keep pace with our marketing efforts. Do also note the error message in the bottom corner that prevents the redirects from being saved.

As mentioned, we have analyzed the existing redirects and even re-input them after the error shown below presented. We've additionally input <US> as the geo-restriction for the new rewrites, but that doesn't resolve the error. This only started happening after the new console experience was implemented.

<img width="1724" alt="Screenshot 2024-05-28 at 5 51 39 PM" src="https://github.com/aws-amplify/amplify-backend/assets/3373091/077c2ba6-d558-428a-94da-0ca8cac7bc28">

We presently have 244 total redirects. Is it possible we've hit an unpublished limit to what Amplify can accept?

**Comment by adsoink** [comment] 2024-05-29 02:28
Hi Jay,

Additional observations - 

- The region-based redirects were initially input over six months ago. There was no error with the redirection feature until the new console experience was implemented.

- Removing all of the geo-restrictions, hitting save, and re-inputting all of the region-based restrictions produces the same error. This behavior leads me to think there's some kind of cache that needs to be purged.

I'm also unable to access the text editor. It gives me a flat version of the JSON file and no means to edit it within the UI. Is this typical behavior? If yes, the notion of "open text editor" is a misnomer and should likely be removed so as to mitigate confusion with new users.

**Comment by Jay2113** [comment] 2024-05-30 03:54
@adsoink thanks for providing us the additional context its very helpful. We are actively investigating to narrow down the root cause of the issue. In the meantime, can you share your Amplify app id?

**Comment by adsoink** [comment] 2024-05-30 04:00
Hi Jay,

Given the generous time between replies, I rebuilt the redirections by hand. Had you replied in a timely manner, I would give you regression steps. 

You can close this topic.

**Comment by Jay2113** [comment] 2024-06-05 16:37
Hi Travis, 

The Amplify open-source team is actively engaged in addressing a variety of issues and this issue was reviewed promptly after being opened. We requested further information and regression steps as we weren't able to reproduce the behavior on our end.

The last statement in your comment has been redacted as it does not adhere to our community's code of conduct. We encourage you to review the [Amazon Open Source Code of Conduct](https://aws.github.io/code-of-conduct) to ensure we maintain a positive and constructive environment for everyone.

I will close this thread as requested. If you are still experiencing any issues, feel free to reach out to me via DM on our [community discord server](https://discord.gg/amplify). My username is `Jay Raval`, and we can schedule a call to discuss them further.

**Closed by Jay2113** 2024-06-05 16:37 UTC
Labels: pending-triage, console
