### ISSUE TITLE
Amplify Console wont load

### ISSUE THREAD

**Issue by jaccorbett** [aws-amplify/amplify-backend#2019] opened 2024-09-18 01:14 UTC
### Environment information

```plain text
N/A

Running Early 2015 MacBook Air
MacOS Monterey V 12.7.3
```

### Describe the bug

When i try to deploy an app following the weblink: https://aws.amazon.com/amplify/

I will log in, then the console screen will never load (see below). 

![Screen Shot 2024-09-18 at 11 04 52 am](https://github.com/user-attachments/assets/95ef0ae3-5244-4cbc-86d8-ccaab31dd224)

### Reproduction steps

N/A

**Comment by ykethan** [comment] 2024-09-18 13:33
Hey @jaccorbett, thank you for reaching out. Tried reproducing this in the [ap-southeast-2 / Sydney](https://ap-southeast-2.console.aws.amazon.com/amplify/apps?region=ap-southeast-2) region but did not observe this loading screen. 
Do you observe an error messages in the browser debug console or any failed network requests?

**Comment by jaccorbett** [comment] 2024-09-23 20:46
@ykethan @Jay2113 thanks for the reply.

Yes, still facing this issue. I can get to work if I open in a browser in a VM, so something specific to my machine OS.


Here is my console log when I try to load the page:


[Info] Successfully preconnected to https://ap-southeast-1.console.aws.amazon.com/amplify/create/global.console.aws.amazon.com
[Info] Successfully preconnected to https://ap-southeast-1.console.aws.amazon.com/amplify/create/a.b.cdn.console.awsstatic.com
[Error] Failed to load resource: the server responded with a status of 403 () (commons.css.map, line 0)
[Error] Failed to load resource: the server responded with a status of 403 () (vendors.css.map, line 0)
[Error] Failed to load resource: the server responded with a status of 403 () (oauthHandler.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 403 () (main.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 403 () (commons.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 403 () (vendors.js.map, line 0)
[Error] SyntaxError: Unexpected token '{'
	(anonymous function) (chunk.752.js:1)
[Error] ChunkLoadError: Loading chunk 752 failed.
(missing: https://a.b.cdn.console.awsstatic.com/a/v1/7XPIQVXRMOZZPSFDG2GBS5LJXBDWDA5UHL6ZPTTNFC6NGCOV7FSQ/chunk.752.js)
	onError (commons.js:10:6796)
	(anonymous function) (commons.js:10:5915)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJobWithoutPromise
	promiseReactionJob
[Error] Failed to load resource: the server responded with a status of 403 () (LegacyRoot.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 403 () (ConsoleV2.css.map, line 0)
[Error] Failed to load resource: the server responded with a status of 403 () (ConsoleV2.js.map, line 0)
[Error] Refused to apply a stylesheet because its hash, its nonce, or 'unsafe-inline' appears in neither the style-src directive nor the default-src directive of the Content Security Policy. (iFrame.html, line 1, x2)
[Error] Blocked a frame with origin "https://ap-southeast-1.console.aws.amazon.com" from accessing a frame with origin "https://global.console.aws.amazon.com". Protocols, domains, and ports must match.
	(anonymous function) (awsc-head.js:2:349772)
[Error] Blocked a frame with origin "https://ap-southeast-1.console.aws.amazon.com" from accessing a frame with origin "https://global.console.aws.amazon.com". Protocols, domains, and ports must match.
	(anonymous function) (commons.js:10:81748)
[Error] Blocked a frame with origin "https://ap-southeast-1.console.aws.amazon.com" from accessing a frame with origin "https://global.console.aws.amazon.com". Protocols, domains, and ports must match.
	(anonymous function) (awsc-head.js:2:349772)
[Error] Blocked a frame with origin "https://ap-southeast-1.console.aws.amazon.com" from accessing a frame with origin "https://global.console.aws.amazon.com". Protocols, domains, and ports must match.
	(anonymous function) (commons.js:10:81748)
[Error] Blocked a frame with origin "https://ap-southeast-1.console.aws.amazon.com" from accessing a frame with origin "https://global.console.aws.amazon.com". Protocols, domains, and ports must match.
	(anonymous function) (awsc-head.js:2:349772)
[Error] Blocked a frame with origin "https://ap-southeast-1.console.aws.amazon.com" from accessing a frame with origin "https://global.console.aws.amazon.com". Protocols, domains, and ports must match.
	(anonymous function) (commons.js:10:81748)
[Error] Blocked a frame with origin "https://ap-southeast-1.console.aws.amazon.com" from accessing a frame with origin "https://global.console.aws.amazon.com". Protocols, domains, and ports must match.
	(anonymous function) (awsc-head.js:2:349772)
[Error] Blocked a frame with origin "https://ap-southeast-1.console.aws.amazon.com" from accessing a frame with origin "https://global.console.aws.amazon.com". Protocols, domains, and ports must match.
	(anonymous function) (commons.js:10:81748)
[Error] Blocked a frame with origin "https://ap-southeast-1.console.aws.amazon.com" from accessing a frame with origin "https://global.console.aws.amazon.com". Protocols, domains, and ports must match.
	(anonymous function) (awsc-head.js:2:349772)
[Error] Blocked a frame with origin "https://ap-southeast-1.console.aws.amazon.com" from accessing a frame with origin "https://global.console.aws.amazon.com". Protocols, domains, and ports must match.
	(anonymous function) (commons.js:10:81748)
[Error] Refused to apply a stylesheet because its hash, its nonce, or 'unsafe-inline' appears in neither the style-src directive nor the default-src directive of the Content Security Policy. (iFrame.html, line 1, x2)
[Error] Refused to apply a stylesheet because its hash, its nonce, or 'unsafe-inline' appears in neither the style-src directive nor the default-src directive of the Content Security Policy. (iFrame.html, line 1, x2)
[Error] Blocked a frame with origin "https://ap-southeast-1.console.aws.amazon.com" from accessing a frame with origin "https://global.console.aws.amazon.com". Protocols, domains, and ports must match.
	(anonymous function) (awsc-head.js:2:349772)
[Error] Blocked a frame with origin "https://ap-southeast-1.console.aws.amazon.com" from accessing a frame with origin "https://global.console.aws.amazon.com". Protocols, domains, and ports must match.
	(anonymous function) (commons.js:10:81748)
[Error] Blocked a frame with origin "https://ap-southeast-1.console.aws.amazon.com" from accessing a frame with origin "https://global.console.aws.amazon.com". Protocols, domains, and ports must match.
	(anonymous function) (awsc-head.js:2:349772)
[Error] Blocked a frame with origin "https://ap-southeast-1.console.aws.amazon.com" from accessing a frame with origin "https://global.console.aws.amazon.com". Protocols, domains, and ports must match.
	(anonymous function) (commons.js:10:81748)
[Error] Blocked a frame with origin "https://ap-southeast-1.console.aws.amazon.com" from accessing a frame with origin "https://global.console.aws.amazon.com". Protocols, domains, and ports must match.
	(anonymous function) (awsc-head.js:2:349772)
[Error] Blocked a frame with origin "https://ap-southeast-1.console.aws.amazon.com" from accessing a frame with origin "https://global.console.aws.amazon.com". Protocols, domains, and ports must match.
	(anonymous function) (commons.js:10:81748)
[Error] Blocked a frame with origin "https://ap-southeast-1.console.aws.amazon.com" from accessing a frame with origin "https://global.console.aws.amazon.com". Protocols, domains, and ports must match.
	(anonymous function) (awsc-head.js:2:349772)
[Error] Blocked a frame with origin "https://ap-southeast-1.console.aws.amazon.com" from accessing a frame with origin "https://global.console.aws.amazon.com". Protocols, domains, and ports must match.
	(anonymous function) (commons.js:10:81748)
[Error] Refused to apply a stylesheet because its hash, its nonce, or 'unsafe-inline' appears in neither the style-src directive nor the default-src directive of the Content Security Policy. (iFrame.html, line 1)
[Error] Refused to apply a stylesheet because its hash, its nonce, or 'unsafe-inline' appears in neither the style-src directive nor the default-src directive of the Content Security Policy. (iFrame.html, line 1)
[Error] Refused to apply a stylesheet because its hash, its nonce, or 'unsafe-inline' appears in neither the style-src directive nor the default-src directive of the Content Security Policy. (iFrame.html, line 1)

**Comment by ykethan** [comment] 2024-09-24 19:22
Hey @jaccorbett, thank you for the information. To confirm are you currently behind a proxy network that may be blocking the requests?

**Comment by Jay2113** [comment] 2024-09-30 13:49
@jaccorbett if you are still running into this issue we recommend the following:
- If you are connected to a corporate network via VPN, disconnect it and try again
- Reach out to your network administrator to rule out firewall issues
- If you are unable to access the console on your computer and it works on other devices such as mobile phone try flushing your DNS cache. You can learn more about it [here](https://nordvpn.com/blog/flush-dns/)

Closing this thread as we are unable to reproduce this issue and the root cause seems to be a network and/or client configuration issue.

**Closed by Jay2113** 2024-09-30 13:49 UTC
Labels: pending-triage, pending-response, console
