### ISSUE TITLE
AWS Amplify for React SPA: Build gets stuck when extracting the cache.

### ISSUE THREAD

**Issue by iberth-vantiva** [aws-amplify/amplify-backend#1772] opened 2024-07-22 18:32 UTC
### Environment information

```plain text
19 2024-07-22T18:24:05.065Z [INFO]: ---- Setting Up SSM Secrets ----
20 2024-07-22T18:24:05.065Z [INFO]: SSM params {"Path":"/amplify/dgp1n8jvmw3zu/main/","WithDecryption":true}
21 2024-07-22T18:24:05.119Z [WARNING]: !Failed to set up process.env.secrets
22 2024-07-22T18:24:06.187Z [INFO]: No live updates for this build run
23 2024-07-22T18:24:06.190Z [INFO]: # Retrieving cache...
24 2024-07-22T18:25:01.871Z [INFO]: # Extracting cache...
```

### Description

It gets stuck at this step:
```
2024-07-22T18:24:06.190Z [INFO]: # Retrieving cache...
2024-07-22T18:25:01.871Z [INFO]: # Extracting cache...
```

**Comment by Avinash-Ch-Technicolor** [comment] 2024-07-22 18:32
I am also facing the same issue.

**Comment by TomBell95** [comment] 2024-07-23 11:20
I'm also getting this issue - nothing has changed our side to cause this. Added $(pnpm store path) as per @Jay2113's [comment](https://github.com/aws-amplify/amplify-backend/issues/1765#issuecomment-2243243406) but still not resolved.

Any help?

**Comment by Jay2113** [comment] 2024-07-23 14:26
@Avinash-Ch-Technicolor can you share your Amplify app id?

**Comment by Jay2113** [comment] 2024-07-23 15:58
@iberth-vantiva @Avinash-Ch-Technicolor We have identified the root cause of the issue. Please find the details below:

Amplify experienced a problem extracting cache artifacts for `pnpm` builds in the regions `ca-central-1`, `eu-south-1`, `us-east-2`, `us-east-1`, `eu-west-1`, and `ap-southeast-1`. The issue has been resolved and the service is operating normally. You can retry any failed deploys from the Amplify Console.

Can you please retry and confirm if you are now unblocked?

**Comment by iberth-vantiva** [comment] 2024-07-23 16:19
@Jay2113 Confirming that this is back to normal now, we are not experiencing this issue anymore.

Thank you so much for the quick action & resolution.

**Comment by Jay2113** [comment] 2024-07-24 13:38
I am closing this thread since the issue has been resolved.

**Closed by Jay2113** 2024-07-24 13:38 UTC
Labels: bug, console-builds
