### ISSUE TITLE
How enable SSR logs for existing Amplify App

### ISSUE THREAD

**Issue by ashokvaddevalli** [aws-amplify/amplify-backend#2197] opened 2024-11-05 15:23 UTC
### Environment information

```plain text
Enable SSR logs for existing Amplify App.
We are missed to enable SSR logs during create app but we want enable now for existing App. But we didn't see any options in settings for enable SSR logs for exiting App.
```

### Describe the feature

Enable SSR logs for existing Amplify App.
We are missed to enable SSR logs during create app but we want enable now for existing App. But we didn't see any options in settings for enable SSR logs for exiting App.

### Use case

Enable SSR logs for exiting Amplify App.
We are missed to enable SSR logs during create app but we want enable now for existing App. But we didn't see any options in settings for enable SSR logs for existing App.

**Comment by Jay2113** [comment] 2024-11-08 21:33
Closing as duplicate of https://github.com/aws-amplify/amplify-hosting/issues/3964#issuecomment-2460482396.

**Closed by Jay2113** 2024-11-08 21:33 UTC
Labels: pending-triage, hosting
