### ISSUE TITLE
Pull Request previews not getting generated

### ISSUE THREAD

**Issue by chrowe** [aws-amplify/amplify-backend#1892] opened 2024-08-20 19:41 UTC
### Environment information

```plain text
n/a
```

### Description

Looking at https://docs.aws.amazon.com/amplify/latest/userguide/pr-previews.html it says... "On the Manage preview settings page, turn on Pull request previews. Then choose Confirm." but I can't find the "Manage preview settings page" page.

**Comment by Jay2113** [comment] 2024-08-20 23:59
Hi @chrowe 👋 , thanks for reaching out! You can access the web previews feature as follows:
- Login to the Amplify console and select the target Amplify app
- From the `Overview` pane, select `Hosting`
- Next, select `Previews`. Attached a screenshot for reference:
<img width="1089" alt="Screenshot 2024-08-21 at 5 21 11 AM" src="https://github.com/user-attachments/assets/884d6317-a18f-4387-b1d0-9f76c31dadd0">

- Select the branch and click on `Edit settings`
- Lastly, toggle the pull request previews button to enable the feature and select `Confirm`. Attached a screenshot for reference:

<img width="534" alt="Screenshot 2024-08-21 at 5 21 20 AM" src="https://github.com/user-attachments/assets/6bc07a29-455b-4713-a7fa-46c08195a3f2">

Please note that for security purposes, previews are disabled for public repositories with Amplify backend templates.

**Comment by chrowe** [comment] 2024-08-21 02:04
Ok, I guess I missed the fact that there is a "Manage preview settings" for each branch. It is enabled for the main branch, but we still are not getting builds for all PRs applied to the main branch. 

It looks like maybe the PRs we are having issues with were originally created against another branch and then changed to main. Does the that not trigger a build?

**Comment by Jay2113** [comment] 2024-08-21 23:58
@chrowe If a pull request is initially created against a different base branch, such as `staging`, and later if the base branch is changed to `main`, it will not trigger a new build in Amplify. This is an expected behavior and the only workaround is to close the existing pull request and open a new one targeting the `main` branch.

**Comment by Jay2113** [comment] 2024-08-30 19:23
Closing this thread since the described behavior is expected. I'll recommend raising a feature request on the hosting [repository](https://github.com/aws-amplify/amplify-hosting/issues/new?assignees=&labels=feature-request&projects=&template=1.feature_request.yaml) for triggering a new build in Amplify when the base branch is changed for an existing pull request.

**Closed by Jay2113** 2024-08-30 19:23 UTC
Labels: question, pending-response, hosting
