### ISSUE TITLE
New Environments Popped up

### ISSUE THREAD

**Issue by akilisosa** [aws-amplify/amplify-backend#1577] opened 2024-05-28 22:54 UTC
### Environment information

```plain text
I think this might amplify gen 1 issue. it is crazy though.
```

### Description

![Screenshot 2024-05-28 095426](https://github.com/aws-amplify/amplify-backend/assets/18223349/50d5e6de-2783-42e2-83fb-1606196d1197)

I have no idea how this happened. I am the sole developer on this project. I was working on my project called artscope. I created a branch prod, and then i saw these two other environments pop up. "kelcey" which was created around 12:54 am and "leoine": that was created at 11:23 pm  . 

I did not create them. I have no idea what they are or what they were from. I deleted them when i saw then in the morning. This is the first time something like this has ever happened.

**Comment by ykethan** [comment] 2024-05-29 13:35
Hey @akilisosa, thank you for reaching out. Could you check the the CloudTrail events on the AWS console, with the event type as `CreateBackendEnvironment`. The event should provide information on the user entity that initiated the request.

cc: @Jay2113

**Comment by akilisosa** [comment] 2024-05-30 02:48
Thank you it seems like they are comming from an account i just deleted on the iam console, and they are originating from this ip address: 34.228.4.223  - which it says is the amazon data center. i can share more details but i didn't want to post all that on github

**Comment by Jay2113** [comment] 2024-06-03 15:30
@akilisosa thanks for verifying it. Are you trying to perform full stack deployments? Can these backend environments be created as part of connecting a new branch or as part of a pull request preview branch? 

For example, if you connected a new git branch named `test` without connecting it to an existing backend environment and if it is setup for fullstack deployments a new backend environment will be created with a random name. This can also occur for pull request previews as shown below:

![Screenshot 2024-06-03 at 8 21 26 AM](https://github.com/aws-amplify/amplify-backend/assets/38470430/88033f1a-3467-440c-9837-4a432602fa2b)

Lastly, are you still experiencing this issue after deleting the backend environments and performing a new deployment on existing branches? Can you share the Amplify app id?

**Comment by akilisosa** [comment] 2024-06-08 15:51
Thank you Jay. I was freaking out when I first saw the environments because I thought I was being hacked or something but you are correct this is exactly what is happening. 

I have been a long time user of amplify and when this new update came in I was a little overwhelmed with the changes. I need to sign up for your developer news or something so I can be more in the loop. 

I do still have a problem with the way the amplify app overall menu navigates on my account, I raised the issue with AWS through their bug reporting channel and sent in a video. There is a work around, clicking the tabs and then navigating but I'm sure you will get to it. If you want me to open a separate issue I can do that. Anyway thank you so much keep up the good work!

**Comment by ykethan** [comment] 2024-06-10 15:53
Hey @akilisosa, thank you for the confirmation. Thank you for reporting on this, was this using the feedback button on the Amplify console or via the AWS support?
 It would be great if you could open a new issue for the navigation this would help in tracking this publicly and folks who might run into this and use the workaround.

**Comment by Jay2113** [comment] 2024-06-20 05:04
Closing this thread since the original issue was root caused. @akilisosa if you are experiencing any other issues, please feel free to open a new issue and we will look into it. Thanks!

**Closed by Jay2113** 2024-06-20 05:04 UTC
Labels: pending-triage, pending-response, console
