### ISSUE TITLE
[New Amplify Console UI] Set up continuous deploys with Backend / Connection to Backend UI is not consistent 

### ISSUE THREAD

**Issue by biller-aivy** [aws-amplify/amplify-backend#1463] opened 2024-05-08 11:30 UTC
### Environment information

```plain text
---
```

### Description

When I open the Modal which shows the connection to the Backend App und the Env it is not consistent. In some Apps the setting shows the current app, which is not correct, in other cases it shows the "Select an App". 
When I change the value, save and refresh the page, it shows the old value instead of the saved new one. 

The res from the database is correct I guess: 

```
"branches" : [ {
    "activeJobId" : "0000000135",
    "associatedResources" : null,
    "backend" : null,
    "backendEnvironmentArn" : "arn:aws:amplify:eu-central-1:327300291334:apps/d36kyjopucs8j3/backendenvironments/develop",
    "basicAuthCredentials" : null,
    "branchArn" : "arn:aws:amplify:eu-central-1:327300291334:apps/d2cdz5219eppoi/branches/develop",
    "branchName" : "develop",
    "buildSpec" : null,
    "createTime" : 1.630061191167E9,
    "customDomains" : null,
    "description" : null,
    "destinationBranch" : null,
    "displayName" : "develop",
    "enableAutoBuild" : false,
    "enableBasicAuth" : false,
    "enableNotification" : false,
    "enablePerformanceMode" : false,
    "enablePullRequestPreview" : false,
    "environmentVariables" : {
      "AMPLIFY_BACKEND_APP_ID" : "d36kyjopucs8j3",
      "AMPLIFY_BACKEND_PULL_ONLY" : "true",
      "USER_BRANCH" : "develop"
    },
    "framework" : "Expo-Web",
    "pullRequestEnvironmentName" : null,
    "sourceBranch" : null,
    "stage" : "DEVELOPMENT",
    "tags" : { },
    "thumbnailUrl" : null,
    "totalNumberOfJobs" : "0",
    "ttl" : "5",
    "updateTime" : 1.71516066086E9
  }
```

**Comment by Jay2113** [comment] 2024-05-08 22:45
@biller-aivy thanks for reaching out. I was able to reproduce this behavior and marking this as a bug. We are working on prioritizing a fix for it and will keep you posted with any updates.

**Comment by Jay2113** [comment] 2024-06-20 04:23
@biller-aivy 👋 , we have deployed a fix for this issue and the backend environment connection (across apps) should now persist in the console. Can you please confirm if you are unblocked? Thanks!

**Comment by Jay2113** [comment] 2024-06-26 17:10
Closing this thread since a fix has been deployed.

**Closed by Jay2113** 2024-06-26 17:10 UTC
Labels: bug, pending-response, console
