### ISSUE TITLE
ctrl + c on create flow throws stack trace with `Error: User force closed the prompt with 0 null`

### ISSUE THREAD

**Issue by ykethan** [aws-amplify/amplify-backend#1001] opened 2024-02-06 21:51 UTC
### Environment information

```plain text
System:
    OS: macOS 14.3
    CPU: (8) arm64 Apple M1
    Memory: 260.28 MB / 16.00 GB
    Shell: 3.6.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 21.6.1 - ~/.local/share/nvm/v21.6.1/bin/node
    Yarn: Not Found
    npm: 10.2.4 - ~/.local/share/nvm/v21.6.1/bin/npm
    pnpm: 7.26.2 - /opt/homebrew/bin/pnpm
    bun: Not Found
    Watchman: Not Found
  npmPackages:
    @aws-amplify/backend: ^0.11.0 => 0.11.0 
    @aws-amplify/backend-cli: ^0.11.0 => 0.11.0 
    aws-amplify: ^6.0.15 => 6.0.15 
    aws-cdk: ^2.126.0 => 2.126.0 
    aws-cdk-lib: ^2.126.0 => 2.126.0 
    typescript: ^5.3.3 => 5.3.3
```

### Description

<img width="911" alt="image" src="https://github.com/aws-amplify/amplify-backend/assets/87995712/8a27771a-d529-4275-8d37-6d0a34d3f82a">

**Comment by josefaidt** [comment] 2024-02-06 22:05
marking as a bug

**Comment by edwardfoyle** [comment] 2024-02-06 23:31
Closing as a duplicate of https://github.com/aws-amplify/amplify-backend/issues/825

**Closed by edwardfoyle** 2024-02-06 23:31 UTC
Labels: bug, create-amplify
