### ISSUE TITLE
preSignUp trigger lambda times out using `callback()` completion method

### ISSUE THREAD

**Issue by johnpc** [aws-amplify/amplify-backend#1021] opened 2024-02-12 22:31 UTC
### Environment information

```plain text
(base) ➜  feb11-autoconfirm-signup git:(main) ✗ npx amplify info

System:
  OS: macOS 14.3
  CPU: (10) arm64 Apple M1 Pro
  Memory: 239.98 MB / 32.00 GB
  Shell: /bin/zsh
Binaries:
  Node: 20.8.1 - ~/.local/share/rtx/installs/node/20.8.1/bin/node
  Yarn: 3.6.4 - ~/.local/share/rtx/installs/node/20.8.1/bin/yarn
  npm: 10.1.0 - ~/.local/share/rtx/installs/node/20.8.1/bin/npm
  pnpm: undefined - undefined
NPM Packages:
  @aws-amplify/backend: 0.12.1
  @aws-amplify/backend-cli: 0.11.1
  aws-amplify: 6.0.16
  aws-cdk: 2.127.0
  aws-cdk-lib: 2.127.0
  typescript: 5.3.3
AWS environment variables:
  AWS_STS_REGIONAL_ENDPOINTS = regional
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
No CDK environment variables
```

### Description

When using a preSignUp lambda like this:

```typescript
// amplify/auth/pre-sign-up-handler.ts
import type {PreSignUpTriggerHandler} from "aws-lambda";

export const handler: PreSignUpTriggerHandler = async (
  event,
  context,
  callback
) => {
  // Uncommenting the following line fixes the issue
  // context.callbackWaitsForEmptyEventLoop = false;
  return callback(null, event);
};
```

the sign up consistently times out. Adding `context.callbackWaitsForEmptyEventLoop = false;` to the lambda causes it to succeed. Additionally, changing `return callback(null, event);` to `return event;` also fixes the issue.

However, I would not expect usage of the `callback()` completion strategy to lead to lambda timeouts.

A full reproduction is available here: https://github.com/johnpc/autoconfirm-signup-authenticator-bug

**Comment by edwardfoyle** [comment] 2024-02-15 20:58
This is due to the ssm param refresh that we set in the lambda code: https://github.com/aws-amplify/amplify-backend/blob/main/packages/backend-function/src/lambda-shims/invoke_ssm_shim.ts#L11-L13

We can either treat this as expected behavior and document that async/await handlers are recommended and if you want to use the callback, you need to set `context.callbackWaitsForEmptyEventLoop = false` or we can investigate another strategy for the ssm param refresh mechanism

**Comment by josefaidt** [comment] 2024-06-28 15:29
Closing in favor of the workaround posted above, however can consider releasing handler types that prohibit the use of `callback` in the future

**Closed by josefaidt** 2024-06-28 15:29 UTC
Labels: feature-request, needs-product-input, function
