### ISSUE TITLE
Unsupported file/folder type when uploading updates of flutter web application

### ISSUE THREAD

**Issue by hello96** [aws-amplify/amplify-backend#1650] opened 2024-06-14 07:58 UTC
### Environment information

```plain text
AWS Amplify console from browser (Chrome v. 125.0.6422.142)
```

### Description

Hi everyone! 
Unfortunately I'm getting this error when I try to update my flutter web application, both by drag&drop and by clicking the uploading button. As always I pick the build/web folder's content and compress it in a zip. My region is us-east-2.

What am I missing? The last deploy three days ago went like a charm.

I just asked my colleague to try it, with the same Chrome version and the same zip file he managed to deploy. So strange...

![Screenshot 2024-06-13 172920](https://github.com/aws-amplify/amplify-backend/assets/31999705/ae54f5c9-0b40-4be1-b767-0b5451f8c378)

Thanks for your reply 🙂

**Comment by rlefflerElite** [comment] 2024-06-14 13:29
I am running into the same issue with my Angular app.  I noticed this started either Wednesday or yesterday, since I could deploy on Tuesday.  Prior to this, we were deploying using amplify hosting and amplify publish command.  It seems like our Amplify cloudfront distribution became corrupt and our production front end was down on June 4th.  Not sure if these are connected at all.

**Comment by Jay2113** [comment] 2024-06-14 14:56
@hello96 @rlefflerElite 👋 , thanks for reaching out. While I am working on narrowing down the root cause of this behavior, can you confirm the following details:
- Can you please double check if you are uploading a zip file instead of the entire folder?
- Are you uploading the file from a Windows laptop?

**Comment by hello96** [comment] 2024-06-14 15:01
> @hello96 @rlefflerElite 👋 , thanks for reaching out. While I am working on narrowing down the root cause of this behavior, can you confirm the following details:
> 
> * Can you please double check if you are uploading a zip file instead of the entire folder?
> * Are you uploading the file from a Windows laptop?

- I'm sure I am uploading the zip file;
- Yes, my laptop has Windows 11, my colleague who managed to upload the same zip file has a Mac.

**Comment by rlefflerElite** [comment] 2024-06-14 15:04
> @hello96 @rlefflerElite 👋 , thanks for reaching out. While I am working on narrowing down the root cause of this behavior, can you confirm the following details:
> 
> * Can you please double check if you are uploading a zip file instead of the entire folder?
> * Are you uploading the file from a Windows laptop?

Very sure I am uploading a zip file. Have had two other team members try as well
We have all tried on Windows 11.  2 are laptops, and one is desktop

**Comment by Jay2113** [comment] 2024-06-14 15:11
Thanks for the confirmation @hello96 @rlefflerElite. We have root caused the issue and are actively working on a fix. I am marking this as a bug.

**Comment by Jay2113** [comment] 2024-06-14 16:15
@hello96 @rlefflerElite, this issue has now been fixed. Can you try to upload the zip file again? Please let us know how it goes. 

Thanks for your patience and for reporting the issue.

**Comment by hello96** [comment] 2024-06-14 16:18
> @hello96 @rlefflerElite, this issue has now been fixed. Can you try to upload the zip file again? Please let us know how it goes.
> 
> Thanks for your patience and for reporting the issue.

I'm allowed to upload the zip again, thanks! 👍

**Comment by rlefflerElite** [comment] 2024-06-14 18:46
I found a Mac and deployed on that this morning. Will try next week.  Thanks for the quick response!

**Comment by Jay2113** [comment] 2024-06-17 18:25
I am going to close this thread since the issue is resolved. Please feel free to reopen it if you are still experiencing any issues. Thanks!

**Closed by Jay2113** 2024-06-17 18:25 UTC
Labels: bug, console
