### ISSUE TITLE
Request to Grant "cognito-idp:ListUsers" access to auth resources

### ISSUE THREAD

**Issue by Zhuohui-Li** [aws-amplify/amplify-backend#1459] opened 2024-05-07 23:39 UTC
### Environment information

```plain text
System:
  OS: macOS 14.4
  CPU: (10) arm64 Apple M1 Pro
  Memory: 145.25 MB / 16.00 GB
  Shell: /bin/zsh
Binaries:
  Node: 20.12.2 - /private/var/folders/h8/0sklzj9n1pz2zjt34vl3t15w0000gn/T/xfs-f99c7d2a/node
  Yarn: 4.1.1 - /private/var/folders/h8/0sklzj9n1pz2zjt34vl3t15w0000gn/T/xfs-f99c7d2a/yarn
  npm: 10.5.0 - ~/.nvm/versions/node/v20.12.2/bin/npm
  pnpm: undefined - undefined
NPM Packages:
  @aws-amplify/backend: 1.0.0
  @aws-amplify/backend-cli: 0.16.0
  aws-amplify: 6.2.0
  aws-cdk: 2.139.0
  aws-cdk-lib: 2.139.0
  typescript: 5.4.5
AWS environment variables:
  AWS_STS_REGIONAL_ENDPOINTS = regional
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
No CDK environment variables
```

### Description

I tried 
```typescript
const result = await cognitoIdentityProviderClient.send(
      new ListUsersCommand(params),
    );
```
but got
`because no identity-based policy allows the cognito-idp:ListUsers action`

Also, if I used
```typescript
const userpool = backend.auth.resources.userPool as cognito.UserPool;
backend.adminQuery.resources.lambda.addToRolePolicy(
  new iam.PolicyStatement({
    actions: ["cognito-idp:ListUsers"],
    resources: [userpool.userPoolArn],
  }),
);
```
to provide necessary access,
it throwed `Deployment failed: Error [ValidationError]: Circular dependency between resources: [storage, adminQueryApi, auth, apiGatewayStack, data, function]`

`resources: ["*"]` worked fine

**Comment by ykethan** [comment] 2024-05-08 13:46
Hey @Zhuohui-Li, thank you for reaching out. The issue appears to be similar to https://github.com/aws-amplify/amplify-backend/issues/1375 with a workaround on the comment: https://github.com/aws-amplify/amplify-backend/issues/1375#issuecomment-2079388509.

**Comment by edwardfoyle** [comment] 2024-05-08 16:05
Closing as a duplicate of https://github.com/aws-amplify/amplify-backend/issues/1375

**Closed by edwardfoyle** 2024-05-08 16:05 UTC
Labels: pending-triage, pending-response, function
