### ISSUE TITLE
Circular Error when use custom message via AWS Amplify trigger

### ISSUE THREAD

**Issue by dukeho1996** [aws-amplify/amplify-backend#2247] opened 2024-11-19 19:19 UTC
### Environment information

```plain text
System:
  OS: macOS 15.0.1
  CPU: (10) arm64 Apple M1 Pro
  Memory: 141.30 MB / 16.00 GB
  Shell: /bin/zsh
Binaries:
  Node: 22.9.0 - ~/.nvm/versions/node/v22.9.0/bin/node
  Yarn: 1.22.22 - ~/.yarn/bin/yarn
  npm: 10.8.3 - ~/.nvm/versions/node/v22.9.0/bin/npm
  pnpm: undefined - undefined
NPM Packages:
  @aws-amplify/auth-construct: 1.5.0
  @aws-amplify/backend: 1.7.0
  @aws-amplify/backend-auth: 1.4.0
  @aws-amplify/backend-cli: 1.4.2
  @aws-amplify/backend-data: 1.2.0
  @aws-amplify/backend-deployer: 1.1.9
  @aws-amplify/backend-function: 1.7.5
  @aws-amplify/backend-output-schemas: 1.4.0
  @aws-amplify/backend-output-storage: 1.1.3
  @aws-amplify/backend-secret: 1.1.5
  @aws-amplify/backend-storage: 1.2.2
  @aws-amplify/cli-core: 1.2.0
  @aws-amplify/client-config: 1.5.2
  @aws-amplify/deployed-backend-client: 1.4.2
  @aws-amplify/form-generator: 1.0.3
  @aws-amplify/model-generator: 1.0.9
  @aws-amplify/platform-core: 1.2.0
  @aws-amplify/plugin-types: 1.4.0
  @aws-amplify/sandbox: 1.2.5
  @aws-amplify/schema-generator: 1.2.5
  aws-amplify: 6.8.2
  aws-cdk: 2.167.1
  aws-cdk-lib: 2.167.1
  typescript: 5.6.3
No AWS environment variables
No CDK environment variables
```

### Describe the bug

Hi,
I want to send a temporary password and the verification code in the email. I'm using the signUp function from aws-amplify/auth to create a new user and set the 'custom:temporaryPassword' attribute.

I'm also using the defineAuth function from @aws-amplify/backend to define and configure auth resource. In this configuration, I have described the 'custom:temporaryPassword' attribute as a custom user attribute and set the customMessage trigger to a custom Lambda function customSignUpEmail/resource.

```
import { defineAuth } from '@aws-amplify/backend';
import { customMessage as customMessageLambda } from './customSignUpEmail/resource';

export const auth = defineAuth({
  loginWith: {
    email: true,
  },
  groups: ['MERCHANT_ADMIN', 'MERCHANT_VIEWER'],
  userAttributes: {
    'custom:temporaryPassword': {
      dataType: 'String',
    },
  },
  triggers: {
    customMessage: customMessageLambda,
  },
});
```

However, I get this error
failed: ValidationError: Circular dependency between resources: [storage0EC3F24A, auth179371D7, data7552DF31, CustomVerifiedPermissions4A29311F, function1351588B, AmplifyStack7460781E]

I attached my backend.ts here 
[message.txt](https://github.com/user-attachments/files/17820355/message.txt)

### Reproduction steps

Run `npx ampx sandbox --profile wlnzportalsdev --debug --once` 
Circular error will show up

**Comment by ykethan** [comment] 2024-11-26 21:34
Hey, noticed the issue is similar to this thread on discord https://discord.com/channels/705853757799399426/1308506396626784337/1308506396626784337

Do let us know if the comments help mitigate the issue.

**Comment by ykethan** [comment] 2024-12-05 17:38
with the latest release the `defineFunction` properties now includes `resourceGroupName` which should allows you to group the function with other resource categories and should help with the circular dependency issues. 
I would try setting the resourceName as data and retry the sandbox build

```
import { defineFunction } from "@aws-amplify/backend";

export const uploadFunction = defineFunction({
  name: "upload-function",
  entry: "./handler.ts",
  resourceGroupName: "data", // groups with data resource
});
```

Closing this issue, do reach out if you require any additional assistance.

**Closed by ykethan** 2024-12-05 17:38 UTC
Labels: sandbox, pending-triage, pending-response, pending-community-response
