### ISSUE TITLE
[CICD] Windows run_e2e_tests failure running `npm create amplify@beta --yes`

### ISSUE THREAD

**Issue by rtpascual** [aws-amplify/amplify-backend#1162] opened 2024-03-18 15:56 UTC
### Description

Sample run: https://github.com/aws-amplify/amplify-backend/actions/runs/8303242067/job/22756638019#step:8:1641

```
test at file:\D:\a\amplify-backend\amplify-backend\packages\integration-tests\lib\test-e2e\create_amplify.test.js:55:18
✖ starting from module project (93807.0878ms)
  Error: Command failed with exit code 1: npm create amplify@beta --yes
      at makeError (file:///D:/a/amplify-backend/amplify-backend/node_modules/execa/lib/error.js:60:11)
      at handlePromise (file:///D:/a/amplify-backend/amplify-backend/node_modules/execa/index.js:124:26)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at TestContext.<anonymous> (D:\a\amplify-backend\amplify-backend\packages\integration-tests\src\test-e2e\create_amplify.test.ts:92:11)
      at async Test.run (node:internal/test_runner/test:632:9)
      at async Promise.all (index 0)
      at async Suite.run (node:internal/test_runner/test:948:7)
      at async Promise.all (index 1)
      at async Suite.run (node:internal/test_runner/test:948:7)
      at async startSubtest (node:internal/test_runner/harness:214:3) {
    shortMessage: 'Command failed with exit code 1: npm create amplify@beta --yes',
    command: 'npm create amplify@beta --yes',
    escapedCommand: 'npm create "amplify@beta" --yes',
    exitCode: 1,
    signal: undefined,
    signalDescription: undefined,
    stdout: undefined,
    stderr: undefined,
    cwd: 'C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\test-create-amplifybGwDCO',
    failed: true,
    timedOut: false,
    isCanceled: false,
    killed: false
  }
```

**Comment by edwardfoyle** [comment] 2024-03-18 16:01
Based on https://github.com/aws-amplify/amplify-backend/actions/runs/8303242067/job/22756638019#step:8:158 this looks like a dupe of https://github.com/aws-amplify/amplify-backend/issues/1158

**Closed by edwardfoyle** 2024-03-18 16:01 UTC
Labels: testing, flaky
