### ISSUE TITLE
cannot view deployed backend resources or download amplify_output.json

### ISSUE THREAD

**Issue by qiweiii** [aws-amplify/amplify-backend#1630] opened 2024-06-09 14:52 UTC
### Environment information

```plain text
System:
  OS: macOS 14.5
  CPU: (12) arm64 Apple M2 Max
  Memory: 172.50 MB / 32.00 GB
  Shell: /bin/zsh
Binaries:
  Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
  Yarn: 1.22.21 - ~/.nvm/versions/node/v20.9.0/bin/yarn
  npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
  pnpm: 9.2.0 - ~/.nvm/versions/node/v20.9.0/bin/pnpm
NPM Packages:
  @aws-amplify/backend: 1.0.3
  @aws-amplify/backend-cli: 1.0.4
  aws-amplify: 6.3.6
  aws-cdk: Not Found
  aws-cdk-lib: Not Found
  typescript: 5.4.5
AWS environment variables:
  AWS_STS_REGIONAL_ENDPOINTS = regional
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
No CDK environment variables
```

### Description

on console UI, deploy success, but got error:
<img width="1181" alt="image" src="https://github.com/aws-amplify/amplify-backend/assets/32790369/921ae8e2-c839-4c76-928c-aaf5503eb7f2">

**Comment by Jay2113** [comment] 2024-06-10 15:14
Hi @qiweiii 👋 , thanks for reaching out to us. Which [external provider](https://docs.amplify.aws/react/build-a-backend/auth/concepts/external-identity-providers/#configure-external-sign-in-backend) have you configured for the auth resource? From the CloudFormation console, can you verify if that auth resource was deployed successfully? This will help us understand if the issue is isolated to the console not listing the deployed resources.

**Comment by hubab00ba** [comment] 2024-06-10 17:10
Hi @qiweiii , please confirm if it's a duplicate of this [issue](https://github.com/aws-amplify/amplify-backend/issues/1631).

**Comment by ykethan** [comment] 2024-06-10 18:20
Closing the issue as duplicate of https://github.com/aws-amplify/amplify-backend/issues/1631

**Closed by ykethan** 2024-06-10 18:20 UTC
Labels: duplicate, pending-triage, pending-response, console
