### ISSUE TITLE
Can not connect repos and branches to the Gitlab from AWS Amplify

### ISSUE THREAD

**Issue by richardgloris** [aws-amplify/amplify-backend#1490] opened 2024-05-10 10:19 UTC
### Environment information

```plain text
When I trying to connect to the gitlab branches from this page, it is not working
```

### Description

Reproduce step:

1.  Create new app
![image](https://github.com/aws-amplify/amplify-backend/assets/81935266/3a588d3a-e790-4274-b3f7-aafaade8fa67)

2. Connect gitlab
3. Can not see all repos, just can see only repos without any group, other repos under the group, it is not showing.

**Comment by jsmitthimedhin** [comment] 2024-05-13 17:40
Having the same issue here.

**Comment by ykethan** [comment] 2024-05-13 18:15
Hey @richardgloris @jsmitthimedhin, thank you for reaching out. Tried reproducing the issue but did not observe this behavior in `us-east-1`. 

<img width="1433" alt="image" src="https://github.com/aws-amplify/amplify-backend/assets/87995712/793dcb45-0155-4dc5-b25e-925794bdb3d9">

could you let us know the region where you were creating the app?

additionally, could you try removing the authorization application for amplify and retry the app creation.

<img width="837" alt="image" src="https://github.com/aws-amplify/amplify-backend/assets/87995712/5d05145d-cee9-4145-8063-66ad6dd37157">

**Comment by richardgloris** [comment] 2024-05-13 18:22
> Hey @richardgloris @jsmitthimedhin, thank you for reaching out. Tried reproducing the issue but did not observe this behavior in `us-east-1`.
> 
> <img alt="image" width="1433" src="https://private-user-images.githubusercontent.com/87995712/330161062-793dcb45-0155-4dc5-b25e-925794bdb3d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2MjQ0MTcsIm5iZiI6MTcxNTYyNDExNywicGF0aCI6Ii84Nzk5NTcxMi8zMzAxNjEwNjItNzkzZGNiNDUtMDE1NS00ZGM1LWIyNWUtOTI1Nzk0YmRiM2Q5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDE4MTUxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViYTU4ZDhhMTgyZTJkN2EzNTQxMWVmMWY2YzgxMGIzOTU1ZDQyZGFjYjA0NjQwNzA2YjM0MThlNjM4M2RhYmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ku3fwgYTlL0sQmRGlSG4eaXhg7KE7SMdbFxMUCxak-g">
> could you let us know the region where you were creating the app?
> 
> additionally, could you try removing the authorization application for amplify and retry the app creation.
> 
> <img alt="image" width="837" src="https://private-user-images.githubusercontent.com/87995712/330162287-5d05145d-cee9-4145-8063-66ad6dd37157.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2MjQ0MTcsIm5iZiI6MTcxNTYyNDExNywicGF0aCI6Ii84Nzk5NTcxMi8zMzAxNjIyODctNWQwNTE0NWQtY2VlOS00MTQ1LTgwNjMtNjZhZDZkZDM3MTU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDE4MTUxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5NjY1OTU0MDVjMzhkNWJhYzRiMGJkZWU1ODgzODI5ZjJhMGQyODBmMTI4MWNkNWZkNDM3M2ZjNWM2Y2IxZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.v7NTOHiJn-ziEhQrinQYj9j3NSVl_frNTvqn6Ex1ThY">

But for me it is not working still yet, I will show you

https://github.com/aws-amplify/amplify-backend/assets/81935266/1cdcad6f-e845-4595-a2e9-10d3c3c1c10c


As you see, if I will try to create new app, it is not working.
Before I added same repo so I was going to add new branch but it is not working though

**Comment by richardgloris** [comment] 2024-05-13 18:27
@ykethan It is happened at the `eu-central-1`, if it will be helpful for you

**Comment by OOCAZ** [comment] 2024-05-13 19:05
I am working with @jsmitthimedhin, we are trying on us-east-2, on an initial load it will show some of our orgs repos but not all of them and on a second or third try without clearing the cookies it will only show us one of the repos.

**Comment by tonysanib** [comment] 2024-05-14 11:49
Same problem on eu-west-3

**Comment by jsmitthimedhin** [comment] 2024-05-14 13:27
> Hey @richardgloris @jsmitthimedhin, thank you for reaching out. Tried reproducing the issue but did not observe this behavior in `us-east-1`.
> 
> <img alt="image" width="1433" src="https://private-user-images.githubusercontent.com/87995712/330161062-793dcb45-0155-4dc5-b25e-925794bdb3d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2OTMzNDUsIm5iZiI6MTcxNTY5MzA0NSwicGF0aCI6Ii84Nzk5NTcxMi8zMzAxNjEwNjItNzkzZGNiNDUtMDE1NS00ZGM1LWIyNWUtOTI1Nzk0YmRiM2Q5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDEzMjQwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlZTI3ZTQyNjAyY2Y5YjJkYzAxN2FiMWQ4OWMyNmE1MGMxMTVkMTllY2ZhMzFkMTc4MzZkMDBkNTBlZDhiNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Z0lXqImSKchNwmeXGK-f328fL1DFGnw9xOLWSvBPr48">
> could you let us know the region where you were creating the app?
> 
> additionally, could you try removing the authorization application for amplify and retry the app creation.
> 
> <img alt="image" width="837" src="https://private-user-images.githubusercontent.com/87995712/330162287-5d05145d-cee9-4145-8063-66ad6dd37157.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2OTMzNDUsIm5iZiI6MTcxNTY5MzA0NSwicGF0aCI6Ii84Nzk5NTcxMi8zMzAxNjIyODctNWQwNTE0NWQtY2VlOS00MTQ1LTgwNjMtNjZhZDZkZDM3MTU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDEzMjQwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2ODQzMmQyOWQ5YWEwNDY2N2U5Y2FhMTc0Y2MyNDZiODcxNWRjOTA2ZDc3MzhhYWQ1MDMxOGQ3ZmJiZjU5M2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.f6L2C3izp2XsjDqokw5D1bNWKRNDPAGXuD1iIvMC12U">

Just to reply directly here, we've also tried removing the authorization application and retrying to no avail.

**Comment by sarah-chua** [comment] 2024-05-16 09:50
Having the same issue in `us-east-1` and `ap-southeast-1`. Not all repos are being displayed in the dropdown and 'No options found' when I type out the repo manually. Revoking authorized applications did not help, please resolve this soon.

**Comment by swaminator** [comment] 2024-05-17 05:34
@sarah-chua @jsmitthimedhin @tonysanib @OOCAZ @richardgloris can you please share your account ID via a DM on our [community discord server](https://discord.gg/amplify)? My username is swaminator.

**Comment by tonysanib** [comment] 2024-05-24 07:07
What's the latest on this?

**Comment by griffins-planera** [comment] 2024-05-24 20:21
Unfortunately this is still an issue for us. We cannot add new branches to our amplify app. 

Started with a fresh browser session for both Amplify and Gitlab as well.

**Comment by tonysanib** [comment] 2024-05-29 05:29
We also continue to have the same problem, and I find it unbelievable that we continue to have this problem for weeks on an AWS service. Because of this problem, we have lost the ability to automatically deploy to production environments and to connect any branch of our application in Amplify and we are still without a solution.

**Comment by tonysanib** [comment] 2024-06-04 06:54
Today we received the following email from AWS stating that the problem has been resolved and how to proceed:

_Hello,

We are contacting you because we are making a change to the AWS Amplify API which requires your action as soon as possible.

We determined that there was an issue with Oauth connections to GitLab, which affects how AWS Amplify processes changes coming from GitLab. To address this issue, we are re-configuring Oauth applications connected to AWS Amplify. Beginning June 4, 2024, GitLab users will be required to reconnect their Amplify apps with their repositories to help facilitate this change and continue building and updating the Amplify Apps from the source code.

If you do not take action by this date, Amplify will no longer build new changes from your repositories, and you will not be able to update your apps. Your existing Amplify apps will remain online with the code that was deployed before June 4, 2024, but you will not be able to make updates until you reconnect your Amplify apps.

To reconnect your Amplify apps with their respective repositories, we recommend you access the Amplify console and follow the instructions provided in the Amplify console for each of your Amplify apps.

A list of your affected resource(s) can be found in the 'Affected resources' tab of your AWS Health Dashboard.

If you have questions, please contact AWS Support

We have tested and everything is working correctly._ 

Thank you

**Comment by sarah-chua** [comment] 2024-06-04 07:34
Thanks @tonysanib for the update. Just checked and saw this notification in my AWS Health Dashboard too.

I tried checking my affected resources through the AWS Health Dashboard and directly through the Amplify Console but found no instructions provided for reconnecting the Amplify Apps. Not sure if anyone knows the proper way to go about doing this?

**Comment by tonysanib** [comment] 2024-06-04 07:53
@sarah-chua We have simply disconnected and reconnected the branches and it seems to be working properly.

**Comment by griffins-planera** [comment] 2024-06-04 23:12
We have also received the same message from AWS. The latest fix is working for us, and I was able to reconnect the repository to enable future updates without issue.

**Comment by Jay2113** [comment] 2024-06-21 17:21
Hey everyone 👋 , over the past few weeks we've rolled out several fixes for the Gitlab integration with the new Amplify console. As this thread covered multiple issues, we're closing it. If you continue experiencing any problems, please open a new issue. We appreciate your cooperation and patience. Thanks!

**Closed by Jay2113** 2024-06-21 17:21 UTC
Labels: pending-triage, pending-response, console
