### ISSUE TITLE
[FE-BUG] Amplify pagination table bug (fe only)

### ISSUE THREAD

**Issue by rashgaroth** [aws-amplify/amplify-backend#1517] opened 2024-05-15 06:07 UTC
### Environment information

```plain text
-
```

### Description

After i configure the new variable at the new amplify UI, i've got this bug:

<img width="595" alt="image" src="https://github.com/aws-amplify/amplify-backend/assets/50513263/93ad0430-d1ad-4c97-b620-2c112a0c44e7">

i can't scroll to the bottom within the table's container.

<img width="1427" alt="image" src="https://github.com/aws-amplify/amplify-backend/assets/50513263/a0570ed2-b832-4f2b-990a-8fc8036ad2ab">

it'll worked when i zoom out to 80% - 70%

**Comment by Jay2113** [comment] 2024-06-20 05:12
Closing this as a duplicate of #1615 and I'll recommend subscribing to it to track updates on the fix. Thanks!

**Closed by Jay2113** 2024-06-20 05:12 UTC
Labels: bug, console
