### ISSUE TITLE
Add custom resources to amplifyconfiguration.json

### ISSUE THREAD

**Issue by lazpavel** [aws-amplify/amplify-backend#950] opened 2024-01-25 17:30 UTC
### Environment information

```plain text
System:
    OS: Linux 6.7 Arch Linux
    CPU: (24) x64 12th Gen Intel(R) Core(TM) i9-12900HX
    Memory: 116.13 GB / 125.50 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
    Yarn: 1.22.21 - /usr/bin/yarn
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.2/bin/npm
    pnpm: 8.14.3 - ~/.local/share/pnpm/pnpm
    bun: Not Found
    Watchman: Not Found
  npmPackages:
    @aws-amplify/backend: ^0.10.1 => 0.10.1 
    @aws-amplify/backend-cli: ^0.9.6 => 0.9.6 
    aws-amplify: ^6.0.12 => 6.0.12 
    aws-cdk: ^2.121.1 => 2.121.1 
    aws-cdk-lib: ^2.121.1 => 2.121.1 
    typescript: ^5.2.0 => 5.3.3
```

### Description

1. Add a custom resource in the amplify/custom directory
2. Deploy your amplify backend and observe the resources getting created in AWS console
3. In your frontend directory run `npx amplify generate config --branch main --app-id $BACKEND_APP_ID`

Observe the custom resources are not added to the amplifyconfiguration.json

For a custom API gateway resource this makes the following code error with InvalidApiName:

```
...
Amplify.configure(amplifyConfig);
...

const operation = get({
  apiName: 'foo-bar-api',
  path: '/token',
});
```

**Comment by ykethan** [comment] 2024-01-25 17:38
this appears to be a duplicate of https://github.com/aws-amplify/amplify-backend/issues/841.

**Closed by ykethan** 2024-01-25 17:38 UTC
Labels: pending-triage
