### ISSUE TITLE
Error in older deployments 

### ISSUE THREAD

**Issue by hddananjaya** [aws-amplify/amplify-backend#1501] opened 2024-05-13 08:09 UTC
### Environment information

```plain text
Sorry I don't know where I should run this code.
```

### Description

I had multiple next.js apps that were hosted in Amplify Gen 1. Now one of them gives me this error when I try to open it.

For now, I can successfully deploy this app using `aws amplify start-job` command. But the Amplify app does not get triggered when there are new changes in github.

![image](https://github.com/aws-amplify/amplify-backend/assets/19330397/781b22b8-56be-4e51-a680-43784f6b49a8)

**Comment by hddananjaya** [comment] 2024-05-14 05:01
> Hey @hddananjaya, thank you for reaching out. Is this occurring on Safari browser? could you try switching to a different browser? Do you observe any error messages on the browser debug console?

It happens in Brave on PopOS for me and we tested it on Chrome on Ubuntu also. Same issue.

Console:
![image](https://github.com/aws-amplify/amplify-backend/assets/19330397/316ed8d9-6a76-40c3-9852-733dd6e610b4)

**Comment by hddananjaya** [comment] 2024-05-14 06:49
So according to the above error, I assume it tries to work with an invalid URL and fails. I tried to see what this URL is with a bit of debugging but couldn't see it.

One thing that I saw after inspecting the network tab is that the `repositoryCloneMethod` method of this particular project is set as `SSH`. But all of the other projects that work fine are set as `TOKEN`.  Maybe it fails there because SSH one doesn't have a valid HTTP URL as the "repository".

**Comment by hddananjaya** [comment] 2024-05-15 05:59
@ykethan I was able to fix that frontend crashing problem by changing the repository link, but we will need a proper fix. 

```sh
aws amplify update-app --app-id APP_ID --repository https://github.com/myrepo.git --access-token MY_PERSONAL_ACCESS_TOKEN
```

**Comment by ykethan** [comment] 2024-05-16 04:12
@hddananjaya thank you for the finding. I was able to reproduce this issue, marking as bug.

**Comment by ykethan** [comment] 2024-06-13 15:08
Hey @hddananjaya, we have made some improvements to this. Was not able to reproduce the issue on re-testing.
Closing this thread. Do let us know if are still experiencing this issue.

**Closed by ykethan** 2024-06-13 15:08 UTC
Labels: bug, console

**Comment by hddananjaya** [comment] 2024-06-13 18:01
> Hey @hddananjaya, we have made some improvements to this. Was not able to reproduce the issue on re-testing. Closing this thread. Do let us know if are still experiencing this issue.

Hi @ykethan thanks for addressing this. I only had one Amplify project that didn't work properly. I re-created it.
