### ISSUE TITLE
Inconsistent deploy success even with successful builds 

### ISSUE THREAD

**Issue by AlexanderChiclana** [aws-amplify/amplify-backend#1530] opened 2024-05-16 15:11 UTC
### Environment information

```plain text
I can provide other details if needed, but having issues running command 

Using custom image: public.ecr.aws/docker/library/node:18.17.0
```

### Description

I have 30+ production branches on Amplify that have identical codebases. They are Gatsby JS sites which are fairly large and can take up to an hour each to build. They are connected to various webhooks to trigger rebuilds. 

Since the Gen 2 dashboard has gone live we have been experiencing inconsistent deployments across these branches. Typically 4 or 5 out of the 30 branches will fail to deploy after the webhook is triggered, and manually rebuilding them off the same codebase will work inconsistently as well. 

When I review the logs of the failed branches, there is nothing out of the ordinary there and no fatal error messages. The builds which fail to deploy end like this in their logs, which is identical to how the successful build logs finish  

Completed phase: postBuild
Completed Frontend Build
Build completed successfully
Starting caching...
Creating cache artifact...
Created cache artifact
Uploading cache artifact...
Uploaded cache artifact
Caching completed
Starting build artifact upload process...
Uploading build artifact '__artifacts.zip'...
Build artifact upload completed
Starting environment caching...
Uploading environment cache artifact...
Uploaded environment cache artifact
Environment caching completed

![image](https://github.com/aws-amplify/amplify-backend/assets/32306705/31ba87de-994a-4daf-92e1-eb96894ec400)

**Comment by ykethan** [comment] 2024-05-16 20:05
Hey @AlexanderChiclana, thank you for reaching out. Could you provide us your App-Id and region?

**Comment by AlexanderChiclana** [comment] 2024-05-17 16:26
> Hey @AlexanderChiclana, thank you for reaching out. Could you provide us your App-Id and region?

thanks for the quick reply @ykethan 

d3tqwuyiftpxq0

US East (Ohio)
us-east-2

**Comment by Jay2113** [comment] 2024-05-21 02:19
@AlexanderChiclana 👋 , thanks for sharing the app information. We are investigating into it and will keep you posted with our findings.

**Comment by Jay2113** [comment] 2024-06-17 15:17
@AlexanderChiclana 👋 , thanks for your continued patience. We have root caused the build failures for your app and the build process failed since the underlying build container ran out of memory. We have made improvements to the build process to surface the appropriate error message in the console and this should help with the debugging of the build failures.

Since your latest builds have completed successfully, can you please confirm if you are unblocked?

**Comment by Jay2113** [comment] 2024-07-09 06:30
Closing this thread since we have improved the error message visibility in the console. Feel free to reopen this thread if the issue persists. Thanks!

**Closed by Jay2113** 2024-07-09 06:30 UTC
Labels: pending-response, console-builds
